# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_bootstrap.ipynb.

# %% auto 0
__all__ = ['get_card', 'get_page_index', 'modal_content', 'modal_form', 'modal_link', 'download_button']

# %% ../nbs/03_bootstrap.ipynb 5
from fasthtml.common import *
from fasthtml.jupyter import *

from .core import *
from ngrok_token import *

from math import ceil

from io import BytesIO, StringIO
import pandas as pd

# %% ../nbs/03_bootstrap.ipynb 12
def get_card(img_pth,title,description,link="#",img_height=200,txt_height=150,card_width=22):
    "Card with link; make sure outside Div has cls = 'row'"

    img = Div(
        Img(src=img_pth, loading='lazy',cls='card-img-top'),
        style=f"height: {img_height}px; overflow: hidden;", #image size
    )
    txt = Div(
        H5(title, cls="card-title"),
        P(description, cls='card-text text-muted'), # text-muted make the text looks gray
        cls='card-body',
        style=f"height: {txt_height}px;", # text size
    )
    card = Div(img,txt,style=f'width: {card_width}rem;',cls='card')

    # grid arrange the card, and add link
    card_arrange = Div(card,
                       A(href=link, cls='stretched-link'),
                       # p-3 is for padding margin, make sure outside cls='row'
                       cls='col-xs-12 col-sm-6 col-md-6 col-lg-4 p-3',
                       # amplify the card when mouse over it
                       style="transform: rotate(0); transition: transform 0.3s ease;",
                       onmouseover="this.style.transform='scale(1.05)';",
                       onmouseout="this.style.transform='scale(1)';") 

    return card_arrange

# %% ../nbs/03_bootstrap.ipynb 19
def get_page_index(current_page, total_items, items_per_page=12):
    "Get start index and end index given the current page number"
    
    total_pages = ceil(total_items / items_per_page) #ceil returns integer number, ceil(4.2) --> 5
    
    page = max(1, min(current_page, total_pages))  # Ensure page is within valid range
    
    start_index = (current_page - 1) * items_per_page
    end_index = start_index + items_per_page
    
    return start_index, end_index,total_pages

# %% ../nbs/03_bootstrap.ipynb 28
def modal_content(title, *args):
    return Div(
        Div(
            Div(
                H1(title, cls='modal-title fs-5'),
                Button(type='button', data_bs_dismiss='modal', aria_label='Close', cls='btn-close'),
                cls='modal-header'
            ),
            Div(*args, cls='modal-body'),
            cls='modal-content'
        ),
        cls='modal-dialog modal-xl'
    )

# %% ../nbs/03_bootstrap.ipynb 32
def modal_form(*form_content,post, btn_text='Search',cls=None,target_id='modals-window'):
    "Reference: https://htmx.org/examples/modal-bootstrap/"
    modal_button = Form(*form_content, # Input(type='text',id='ssss')
                        Div(
                            Button(btn_text,cls='btn btn-primary py-3'),
                            data_bs_toggle='modal', 
                            data_bs_target=f'#{target_id}'),
                        post=post, 
                        target_id=target_id, 
                        hx_trigger='submit', 
                        cls=cls)

    modal_content =Div(
        Div(
            Div(cls='modal-content'),
            role='document',
            cls='modal-dialog modal-lg modal-dialog-centered'
        ),
        id=target_id,
        style='display: none',
        aria_hidden='false',
        tabindex='-1',
        cls='modal modal-blur fade'
    )
    return modal_button, modal_content

# %% ../nbs/03_bootstrap.ipynb 36
def modal_link(text,post,cls=None,target_id='modals-window'):
    "Reference: https://htmx.org/examples/modal-bootstrap/"
    modal_button = A(text,
                     data_bs_toggle='modal', 
                     data_bs_target=f'#{target_id}',
                     post=post, 
                     target_id=target_id, 
                     cls=cls)

    modal_content =Div(
        Div(
            Div(cls='modal-content'),
            role='document',
            cls='modal-dialog modal-lg modal-dialog-centered'
        ),
        id=target_id,
        style='display: none',
        aria_hidden='false',
        tabindex='-1',
        cls='modal modal-blur fade'
    )
    return modal_button, modal_content

# %% ../nbs/03_bootstrap.ipynb 46
def download_button(*args, **kwargs):
    return Button(
          I(cls='bi bi-download'),
          *args,
          cls='btn btn-outline-secondary btn-sm',
          **kwargs)
