# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_form.ipynb.

# %% auto 0
__all__ = ['get_file_input', 'bytes2df', 'get_input', 'get_button', 'get_input_list', 'get_select', 'get_select_simple',
           'get_select_simple_multiple', 'get_spinner']

# %% ../nbs/03_form.ipynb 3
from fasthtml.common import *
from fasthtml.jupyter import *

from .core import *
from .static import *

import json
import pandas as pd
from math import ceil

# %% ../nbs/03_form.ipynb 10
def get_file_input(label_text,id,**kwargs):
    return Form(
        Label(label_text, fr=id, cls='form-label'),
        Input(type='file', id=id, cls='form-control'),
        **kwargs
    )

# %% ../nbs/03_form.ipynb 13
def bytes2df(bytes_data,file_type):
    if file_type == "csv":
        data_io = StringIO(bytes_data.decode("utf-8"))
        return pd.read_csv(data_io)
    elif file_type == "excel":
        data_io = BytesIO(bytes_data)
        return pd.read_excel(data_io)

# %% ../nbs/03_form.ipynb 18
def get_input(label_text,id,cls=None, type='text',**kwargs):
    return Span(
        Input(type=type, id=id, cls='form-control',placeholder=label_text,**kwargs),
        Label(label_text, fr=id),
        cls=f'form-floating {cls}')

# %% ../nbs/03_form.ipynb 20
def get_button(text,cls,**kwargs):
    return Button(text,cls=f"btn btn-primary {cls}",type='button',**kwargs)

# %% ../nbs/03_form.ipynb 22
def get_input_list(label_text, input_list, id, cls=None, type='text', **kwargs):
    input_div = Div(
        Input(type=type, id=id, cls='form-control', placeholder=label_text, autocomplete="off", **kwargs),
        Label(label_text, fr=id),
        Div(
            *[Div(item, cls='dropdown-item', data_value=item) for item in input_list],
            id=f'{id}-dropdown',
            cls='dropdown-menu'
        ),
        cls=f'form-floating position-relative {cls}'
    )

    script = Script(f"""
    document.addEventListener('DOMContentLoaded', function() {{
        setupAutocomplete('#{id}', '#{id}-dropdown');
    }});
    """)

    return input_div, script

# %% ../nbs/03_form.ipynb 27
def get_select(label_text,option_list,id,cls=None, **kwargs):
    "The first item in the option_list is the default"
    return Div(
        Select(
            Option(option_list[0], value=option_list[0],selected=True),
            *[Option(i, value=i) for i in option_list[1:]],
            id = id,
            cls='form-select',
            **kwargs
        ),
        Label(label_text, fr=id),
        cls=f'form-floating {cls}')


# %% ../nbs/03_form.ipynb 29
def get_select_simple(label_text, select_list,id,cls=None):
    return Div(Select(
        Option(label_text, selected=True,disabled=True),
        *[Option(i,value=i) for i in select_list],
        cls='form-select',
        id = id), cls=cls)

# %% ../nbs/03_form.ipynb 32
def get_select_simple_multiple(label_text, select_list,id,cls=None):
    return Div(Select(
        Option(label_text, selected=True,disabled=True),
        *[Option(i,value=i) for i in select_list],
        cls='form-select',
        multiple=True,
        id = id), cls=cls)

# %% ../nbs/03_form.ipynb 35
def get_spinner(id, cls='d-flex justify-content-center'):
    return Div(Div(
        Span('Loading...', cls='visually-hidden'),
        role='status',
        cls='htmx-indicator spinner-border',
        id=id,
    ),cls=cls)
