# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_pico.ipynb.

# %% auto 0
__all__ = ['Navbar', 'get_accordian']

# %% ../nbs/05_pico.ipynb 5
from fasthtml.common import *
from .core import *

# %% ../nbs/05_pico.ipynb 9
def Navbar(page):
    "Pico nav bar"
    return Nav(
        Ul(
          Li(A('Home', href='/')),
          Li(A(page, href='#'))),
        aria_label='breadcrumb')

# %% ../nbs/05_pico.ipynb 12
def get_accordian(title,context):
    "clickable expand"
    return Details(Summary(title),P(context))
