# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_plot.ipynb.

# %% auto 0
__all__ = ['fh_svg', 'plot_heatmap', 'plot_bar', 'download_svg']

# %% ../nbs/04_plot.ipynb 3
from fasthtml.common import *
from fasthtml.jupyter import *
import pandas as pd

from .core import *
from .static import *
import json

import numpy as np, pandas as pd, seaborn as sns
from matplotlib import pyplot as plt

# %% ../nbs/04_plot.ipynb 9
def fh_svg(func):
    "svg to fasthtml item"
    def wrapper(*args, **kwargs):
        func(*args, **kwargs)

        f = io.StringIO()
        plt.savefig(f, format='svg', bbox_inches='tight')

        f.seek(0)
        svg_data = f.getvalue()
        plt.close()

        return NotStr(svg_data)
    return wrapper

# %% ../nbs/04_plot.ipynb 12
@fh_svg
def plot_heatmap(df, # a matrix of values
     title: str='heatmap', # title of the heatmap
     # figsize: tuple=(4.5,6), # figure size of the heatmap (6,7)
     cmap: str='coolwarm', # color map, default is dark&white
     **kwargs, # arguments for sns.heatmap()
     ):

    "Plot heatmap based on a matrix of values"

    # plt.figure(figsize=figsize)
    sns.heatmap(df, cmap=cmap, center=0, square=True,annot=False,**kwargs)
    # plt.axvline(len(df.columns)//2,color='black', linewidth=0.5)
    plt.ylabel('')
    plt.title(title)

# %% ../nbs/04_plot.ipynb 16
@fh_svg
def plot_bar(df,title='Bar plot',figsize=(4,4)):
    df.plot.barh(legend=False,figsize=figsize)
    plt.xlabel('Score')
    plt.ylabel('')
    plt.title(title)

# %% ../nbs/04_plot.ipynb 20
def download_svg( *args, txt=' Plot',**kwargs):
    return download_button(txt, *args, onclick='downloadSVG(this)',**kwargs)
